services:
  data-master-service:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - redis
    networks:
      - app-network

  data-worker-service:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8082
      - SHADEMAP_API_KEY=${SHADEMAP_API_KEY}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
    depends_on:
      - redis
    networks:
      - app-network

  routing-service:
    image: router:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - data-master-service
      - data-worker-service
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    networks:
      - app-network

volumes:
  redis:

networks:
  app-network:



