apiVersion: v1
kind: Service
metadata:
  name: master-service
  labels:
    app: master
spec:
  selector:
    app: master
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000