apiVersion: v1
kind: Service
metadata:
  name: routing-service
  labels:
    app: router
spec:
  selector:
    app: router
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080