apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker
    labels:
        app: worker
spec:
    replicas: 4
    selector:
        matchLabels:
            app: worker
    template:
        metadata:
            labels:
                app: worker
        spec:
            imagePullSecrets:
                - name: regcred
            nodeSelector:
                agentpool: userpool
            tolerations:
                - key: 'kubernetes.azure.com/scalesetpriority'
                  operator: 'Equal'
                  value: 'spot'
                  effect: 'NoSchedule'
                - key: 'sku'
                  operator: 'Equal'
                  value: 'gpu'
                  effect: 'NoSchedule'
            containers:
                - name: playwright
                  image: hannie2/my-docker-registry:playwright
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8081
                  env:
                      - name: REDIS_URL
                        valueFrom:
                            secretKeyRef:
                                name: redis-url
                                key: redis.url
                      - name: PORT
                        value: '8081'
                      - name: SHADEMAP_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: shademap-api-key
                                key: shademap.api.key
                      - name: MAPBOX_ACCESS_TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: mapbox-access-token
                                key: mapbox.access.token
                      - name: NVIDIA_VISIBLE_DEVICES
                        value: all
                      - name: NVIDIA_DRIVER_CAPABILITIES
                        value: all
                  resources:
                      requests:
                          cpu: 1200m
                          memory: 5000Mi
                      limits:
                          cpu: 1200m
                          memory: 10000Mi
