apiVersion: v1
kind: Deployment
metadata:
    name: scraper
    labels:
        app: scraper
spec:
    replicas: 3
    selector:
        matchLabels:
            app: scraper
    template:
        metadata:
            labels:
                app: scraper
        spec:
            containers:
                - name: playwright
                  image: playwright:latest
                  ports:
                      - containerPort: 8081
                  env:
                      - name: REDIS_URL
                        valueFrom:
                            secretKeyRef:
                                name: redis-url
                                key: redis.url
                      - name: PORT
                        value: '8081'
                      - name: SHADEMAP_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: shademap-api-key
                                key: shademap.api.key
                      - name: MAPBOX_ACCESS_TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: mapbox-access-token
                                key: mapbox.access.token
                  resources:
                      requests:
                          cpu: 500m
                          memory: 500Mi
                      limits:
                          cpu: 500m
                          memory: 500Mi
